=== CredentialEngine/CTDL_Json_Validation_Schema/Production_Schema/competency_framework.json
{
	"$ref": "#/definitions/ceasn:CompetencyFramework",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"definitions": {
		"@id": { "type": "string" },
		"@context": {
			"enum": [ "http://credreg.net/ctdlasn/schema/context/json" ],
			"type": "string"
		},
		"meta:uri": {
			"type": "object",
			"properties": { "@id": { "$ref": "#/definitions/@id_absolute" } }
		},
		"@id_multi": {
			"type": "array",
			"items": { "$ref": "#/definitions/@id" }
		},
		"ceasn:name": { "$ref": "#/definitions/meta:langstring" },
		"meta:string": { "type": "string" },
		"@id_absolute": {
			"type": "string",
			"format": "uri"
		},
		"ceasn:author": { "$ref": "#/definitions/meta:string_multi" },
		"ceasn:rights": { "$ref": "#/definitions/@id_absolute" },
		"ceasn:source": { "$ref": "#/definitions/@id_absolute_multi" },
		"ceterms:ctid": { "$ref": "#/definitions/meta:string" },
		"ceterms:name": { "$ref": "#/definitions/meta:literal" },
		"meta:literal": {
			"anyOf": [
				{ "$ref": "#/definitions/meta:string" },
				{ "$ref": "#/definitions/meta:literal_object" }
			]
		},
		"ceasn:alignTo": { "$ref": "#/definitions/@id_absolute_multi" },
		"ceasn:creator": { "$ref": "#/definitions/pointer:constraint:ReferenceOrganization" },
		"ceasn:license": { "$ref": "#/definitions/@id_absolute" },
		"ceasn:hasChild": { "$ref": "#/definitions/meta:uri_multi" },
		"meta:uri_multi": {
			"type": "array",
			"items": { "$ref": "#/definitions/meta:uri" }
		},
		"ceasn:alignFrom": { "$ref": "#/definitions/@id_absolute_multi" },
		"ceasn:publisher": { "$ref": "#/definitions/pointer:constraint:ReferenceOrganization" },
		"meta:langstring": {
			"type": "object",
			"properties": {
				"de": { "type": "string" },
				"en": { "type": "string" },
				"es": { "type": "string" },
				"pl": { "type": "string" },
				"ru": { "type": "string" },
				"zh": { "type": "string" },
				"en-GB": { "type": "string" },
				"en-US": { "type": "string" }
			}
		},
		"ceasn:identifier": { "$ref": "#/definitions/@id_absolute_multi" },
		"ceasn:inLanguage": { "$ref": "#/definitions/meta:string_multi" },
		"ceasn:conceptTerm": { "$ref": "#/definitions/@id_absolute_multi" },
		"ceasn:dateCreated": { "$ref": "#/definitions/meta:string" },
		"ceasn:derivedFrom": { "$ref": "#/definitions/@id_absolute_multi" },
		"ceasn:description": { "$ref": "#/definitions/meta:langstring" },
		"ceasn:hasTopChild": { "$ref": "#/definitions/@id_absolute_multi" },
		"meta:string_multi": {
			"type": "array",
			"items": { "$ref": "#/definitions/meta:string" }
		},
		"@id_absolute_multi": {
			"type": "array",
			"items": { "$ref": "#/definitions/@id_absolute" }
		},
		"ceasn:localSubject": { "$ref": "#/definitions/meta:langstring_multi" },
		"ceasn:rightsHolder": { "$ref": "#/definitions/pointer:constraint:ReferenceOrganization" },
		"meta:literal_multi": {
			"type": "array",
			"items": { "$ref": "#/definitions/meta:literal" }
		},
		"ceasn:dateValidFrom": { "$ref": "#/definitions/meta:string" },
		"ceterms:description": { "$ref": "#/definitions/meta:literal" },
		"ceterms:socialMedia": { "$ref": "#/definitions/meta:uri_multi" },
		"meta:literal_object": {
			"type": "object",
			"properties": {
				"@id": { "$ref": "#/definitions/@id" },
				"@value": { "$ref": "#/definitions/meta:string" },
				"@language": { "$ref": "#/definitions/meta:string" }
			}
		},
		"ceasn:conceptKeyword": { "$ref": "#/definitions/meta:langstring_multi" },
		"ceasn:dateValidUntil": { "$ref": "#/definitions/meta:string" },
		"ceasn:repositoryDate": { "$ref": "#/definitions/meta:string" },
		"ceasn:dateCopyrighted": { "$ref": "#/definitions/meta:string" },
		"ceasn:tableOfContents": { "$ref": "#/definitions/meta:langstring" },
		"meta:langstring_multi": {
			"type": "array",
			"items": { "$ref": "#/definitions/meta:langstring" }
		},
		"ceterms:subjectWebpage": { "$ref": "#/definitions/meta:uri_multi" },
		"ceasn:educationLevelType": { "$ref": "#/definitions/@id_absolute_multi" },
		"ceasn:CompetencyFramework": {
			"type": "object",
			"required": [ "@type", "@id", "ceasn:description", "ceasn:inLanguage", "ceasn:name", "ceterms:ctid" ],
			"properties": {
				"@id": { "$ref": "#/definitions/@id" },
				"@type": { "enum": [ "ceasn:CompetencyFramework" ] },
				"@context": { "$ref": "#/definitions/@context" },
				"ceasn:name": { "$ref": "#/definitions/ceasn:name" },
				"ceasn:author": { "$ref": "#/definitions/ceasn:author" },
				"ceasn:rights": { "$ref": "#/definitions/ceasn:rights" },
				"ceasn:source": { "$ref": "#/definitions/ceasn:source" },
				"ceterms:ctid": { "$ref": "#/definitions/ceterms:ctid" },
				"ceasn:alignTo": { "$ref": "#/definitions/ceasn:alignTo" },
				"ceasn:creator": { "$ref": "#/definitions/ceasn:creator" },
				"ceasn:license": { "$ref": "#/definitions/ceasn:license" },
				"ceasn:hasChild": { "$ref": "#/definitions/ceasn:hasChild" },
				"ceasn:alignFrom": { "$ref": "#/definitions/ceasn:alignFrom" },
				"ceasn:publisher": { "$ref": "#/definitions/ceasn:publisher" },
				"ceasn:identifier": { "$ref": "#/definitions/ceasn:identifier" },
				"ceasn:inLanguage": { "$ref": "#/definitions/ceasn:inLanguage" },
				"ceasn:conceptTerm": { "$ref": "#/definitions/ceasn:conceptTerm" },
				"ceasn:dateCreated": { "$ref": "#/definitions/ceasn:dateCreated" },
				"ceasn:derivedFrom": { "$ref": "#/definitions/ceasn:derivedFrom" },
				"ceasn:description": { "$ref": "#/definitions/ceasn:description" },
				"ceasn:hasTopChild": { "$ref": "#/definitions/ceasn:hasTopChild" },
				"ceasn:localSubject": { "$ref": "#/definitions/ceasn:localSubject" },
				"ceasn:rightsHolder": { "$ref": "#/definitions/ceasn:rightsHolder" },
				"ceasn:dateValidFrom": { "$ref": "#/definitions/ceasn:dateValidFrom" },
				"ceasn:conceptKeyword": { "$ref": "#/definitions/ceasn:conceptKeyword" },
				"ceasn:dateValidUntil": { "$ref": "#/definitions/ceasn:dateValidUntil" },
				"ceasn:repositoryDate": { "$ref": "#/definitions/ceasn:repositoryDate" },
				"ceasn:dateCopyrighted": { "$ref": "#/definitions/ceasn:dateCopyrighted" },
				"ceasn:tableOfContents": { "$ref": "#/definitions/ceasn:tableOfContents" },
				"ceasn:educationLevelType": { "$ref": "#/definitions/ceasn:educationLevelType" },
				"ceasn:publicationStatusType": { "$ref": "#/definitions/ceasn:publicationStatusType" }
			},
			"additionalProperties": false
		},
		"ceasn:publicationStatusType": { "$ref": "#/definitions/@id_absolute_multi" },
		"pointer:constraint:ReferenceOrganization": {
			"anyOf": [
				{
					"type": "array",
					"required": [ "@id" ],
					"properties": { "@id": { "$ref": "#/definitions/@id_absolute" } },
					"additionalProperties": false
				},
				{
					"type": "array",
					"required": [ "@type" ],
					"properties": {
						"@type": { "enum": [ "ceterms:CredentialOrganization", "ceterms:QACredentialOrganization" ] },
						"ceterms:name": { "$ref": "#/definitions/ceterms:name" },
						"ceterms:description": { "$ref": "#/definitions/ceterms:description" },
						"ceterms:socialMedia": { "$ref": "#/definitions/ceterms:socialMedia" },
						"ceterms:subjectWebpage": { "$ref": "#/definitions/ceterms:subjectWebpage" }
					},
					"additionalProperties": false
				}
			]
		}
	}
}

=== CredentialEngine/CTDL_Json_Validation_Schema/test_data/competency_framework/TechnicalCollegeReadinessEnglish2016.json
{
	"@id": "https://case.georgiastandards.org/ims/case/v1p0/CFDocuments/6b049b04-4720-11e7-8d2d-b41056aae514",
	"@type": "ceasn:CompetencyFramework",
	"@context": "http://credreg.net/ctdlasn/schema/context/json",
	"ceasn:name": { "en-us": "Technical College Readiness English - 2016" },
	"ceterms:ctid": "ce-b835c3a8-d745-35c2-afce-922b6ceab7ff",
	"ceasn:hasChild": [
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b18a284-4720-11e7-bff2-7c33bd4867aa" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1aee0e-4720-11e7-ac1d-20478b8536ed" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1b23ba-4720-11e7-918b-e4c39a71a5f0" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1b5696-4720-11e7-88cb-f8dfe8c9a775" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1b6ec4-4720-11e7-abba-d138e6111b79" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1bd3fa-4720-11e7-ac02-530a4a9a88e1" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c380e-4720-11e7-93cc-e25c9334c543" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c690a-4720-11e7-aa6d-4a5d6f6da5e9" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c9ab0-4720-11e7-90b9-0525fd9403be" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1cb360-4720-11e7-b880-923d9caba4bf" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1ce506-4720-11e7-86b8-1efb6ee7440e" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1d2f5c-4720-11e7-bfa0-28b939e63c8e" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1d9226-4720-11e7-a15f-3d5c5d4321f2" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1da9c8-4720-11e7-91a7-b7a2a81e4e99" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1dddd0-4720-11e7-83c0-1944311b2499" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1df586-4720-11e7-9aee-7fc2e6ef0845" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c80fc-4720-11e7-9ffd-3f12101525ff" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1bb9b0-4720-11e7-b5e8-ff365819e7ff" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1bec5a-4720-11e7-8e89-32353d3babe4" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c05aa-4720-11e7-8e23-7c1ff72b8167" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c1e78-4720-11e7-af35-425d5c3d7762" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c4fb0-4720-11e7-8bfe-caef4658bbb1" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1b3b48-4720-11e7-b3c3-3463ab029b3e" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1e0e4a-4720-11e7-b658-76dba3a47993" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1e2790-4720-11e7-83a4-c05d305c16d8" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1e4004-4720-11e7-a9ff-6c94f3006498" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1e5904-4720-11e7-bbec-6850d94329c6" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1e70b0-4720-11e7-bf0d-de17d6d30ffd" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1b8670-4720-11e7-b48c-a13c54b114dc" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1ba02e-4720-11e7-bcf4-b7c85f1c8397" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1b0844-4720-11e7-b931-9d0f682a8ab1" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1ccc42-4720-11e7-9c3a-5226623e10ae" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1cfd16-4720-11e7-9177-957268c05407" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1d16a2-4720-11e7-8be9-477a077503f8" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1d471c-4720-11e7-8901-847c282ad29b" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1d5ebe-4720-11e7-ba62-2fe4d48aec50" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1d780e-4720-11e7-8615-c92c165e962d" },
		{ "@id": "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1dc2dc-4720-11e7-a207-c6e6741d044a" }
	],
	"ceasn:inLanguage": [ "en" ],
	"ceasn:description": { "en-us": "Technical College Readiness English will emphasize reading comprehension, identifying main ideas, making inferences, and distinguishing between direct statements and supporting ideas. The course will also emphasize sentence structure skills. This course will provide an opportunity for students to review reading and writing skills needed for success in Technical College." },
	"ceasn:hasTopChild": [ "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b18a284-4720-11e7-bff2-7c33bd4867aa", "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1b5696-4720-11e7-88cb-f8dfe8c9a775", "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1c9ab0-4720-11e7-90b9-0525fd9403be", "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1d9226-4720-11e7-a15f-3d5c5d4321f2", "https://case.georgiastandards.org/ims/case/v1p0/CFItems/6b1dddd0-4720-11e7-83c0-1944311b2499" ],
	"ceasn:conceptKeyword": [ { "en-us": "English" } ]
}

=== CredentialEngine/CTDL_Json_Validation_Schema/test_data/competency_framework/ScrumFoundationsLearningObjectives.json
{
  "@context": "http://credreg.net/ctdlasn/schema/context/json",
  "ceasn:name": {
    "en-us": "Scrum Foundations Learning Objectives"
  },
  "@type": "ceasn:CompetencyFramework",
  "@id": "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/8a705a02-ab53-4df4-868c-820ecb06fc23/1519948402714",
  "ceasn:hasTopChild": [
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/c9efe450-6433-4282-bce8-3a44b47c01eb/1519947015873",
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5b1c1222-037b-46eb-90c6-24ca640120b8/1519945992706"
  ],
  "ceasn:description": {
    "en-us": "Scrum framework description"
  },
  "ceterms:ctid": "ce-cdde7387-230a-3916-afd5-1f6a844bc708",
  "ceasn:author": [
    "some author name"
  ],
  "ceasn:creator": [
    "http://example.com?t=creatorurl"
  ],
  "ceasn:inLanguage": [
    "en"
  ],
  "ceasn:alignFrom": [ "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5b1c1222-037b-46eb-90c6-24ca640120b8/1519945992706" ],
  "ceasn:alignTo": [ "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5b1c1222-037b-46eb-90c6-24ca640120b8/1519945992706" ],


  "ceasn:conceptKeyword": [
    {
      "en-us": "keyword 1"
    },
    {
      "en-us": "keyword 2"
    },
    {
      "en-us": "keyword 3"
    },
    {
      "en-us": " credengine "
    }
  ]
}

=== CredentialEngine/CTDL_Json_Validation_Schema/test_data/competency_framework/A test framework for Capella.json
{
  "@context": "http://credreg.net/ctdlasn/schema/context/json",
      "ceasn:conceptKeyword": [
        {
          "en-us": "A concept keyword"
        }
      ],
      "ceasn:inLanguage": [
        "eN"
      ],
      "@type": "ceasn:CompetencyFramework",
      "ceasn:derivedFrom": [
        "http://example.com?t=derivedFrom"
      ],
      "ceasn:name": {
        "en-us": "A test framework for Capella"
      },
      "@id": "https://dev.cassproject.org/api/data/schema.cassproject.org.0.3.Framework/a5509302-a60e-44b2-8a1a-73597fc5f9dd/1521495623958",
      "ceasn:hasTopChild": [
        "https://dev.cassproject.org/api/data/schema.cassproject.org.0.3.Competency/a042e568-e72a-40a9-a841-84fb197c6378/1521495702272"
      ],
      "ceasn:description": {
        "en-us": "A test framework for Capella.\nWhy is publisher uri here? Is the registry uri an example?\nShould be able to save and continue, rather than leaving after save.\nWould be nice if save button was fixed at top so didn't have to scroll update to save - especially if having a save and continue.\nConcept Term: \n- Clicking create or select resulted in a white page with no directions. \nEducationLevelType\n- same issue\nConcept keyword\n- how to enter multiple (found can just enter commas - need help text)\n- entered one, and pressed enter\n  - sent to a search\n  - no cancel, couldn't get back, other than refreshing\nDates\n- use of date picker?\nExport:\nMissing \n- creator\n- creator name\n- publisher\n- publisherName\n- derivedFrom\n- source\n- date created, date valid from, date valid to, date copyrighted\n- Identifier\n- license Url\n- rights text\n- rights holder uri"
      },
      "ceterms:ctid": "ce-6526f801-46b9-3355-ac23-3a634b449d68"
    }
